repositories:
  - name: uzihoon
    url: https://uzihoon.github.io/helm-repository/
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

releases:
  - name: elasticsearch
    namespace: kube-logging
    chart: uzihoon/elasticsearch
  - name: kibana
    namespace: kube-logging
    chart: uzihoon/kibana
  - name: fluentd
    namespace: kube-logging
    chart: uzihoon/fluentd
